import type { Metadata } from "next";
import Link from "next/link";
import { CheckIcon } from "@/components/icons";
import { ProductImage } from "@/components/product-image";
import { getFeaturedProducts } from "@/lib/catalog";

export const metadata: Metadata = { title: "Compra confirmada | QuilGym" };

export default async function ConfirmationPage() {
  const products = await getFeaturedProducts(2);
  return <><header className="checkout-header"><div className="container"><Link href="/" className="wordmark">QUILGYM</Link><span>Pedido confirmado</span></div></header><main className="confirmation-page"><div className="container"><section className="confirmation-hero"><span><CheckIcon/></span><div><p className="eyebrow">PAGO APROBADO</p><h1>¡Gracias por tu compra, Martina!</h1><p>Tu pedido ya está confirmado. Enviamos el comprobante y las novedades a martina.ruiz@email.com.</p></div><div><small>NÚMERO DE ORDEN</small><strong>QG-2026-18472</strong></div></section><div className="confirmation-actions"><button type="button" className="button button--outline">⌖ Seguir mi pedido</button><button type="button" className="button button--outline">⇩ Descargar comprobante</button><span>Compra realizada el 3 de octubre de 2026 · 20:14 h</span></div><section className="confirmation-cards"><article><span>▣</span><h2>Entrega</h2><strong>ENVÍO ESTÁNDAR · GRATIS</strong><h3>Llega martes 6 o miércoles 7</h3><p>Alvear 742, Quilmes, Buenos Aires (1878) · Martina Ruiz</p></article><article><span>▤</span><h2>Pago</h2><strong>APROBADO</strong><h3>Visa terminada en 7391</h3><p>3 cuotas sin interés de $29.928<br/><b>Total: $89.784</b></p></article><article><span>▥</span><h2>Opción de retiro</h2><h3>Preferís retirar en tienda</h3><p>Podés cambiar a retiro gratis en Quilmes Centro antes de que preparemos el envío.</p><a href="#">Cambiar a retiro →</a></article></section><div className="confirmation-grid"><section className="order-detail"><header><h2>Detalle del pedido</h2><span>3 productos</span></header>{products.map((product,index) => <article key={product.slug}><ProductImage product={product} sizes="72px" decorative/><div><strong>{product.name}</strong><small>{product.category.name} · Cantidad {index + 1}</small></div><b>${(product.priceArs * (index + 1)).toLocaleString("es-AR")}</b></article>)}<div className="order-total"><p><span>Subtotal</span><b>$99.760</b></p><p><span>Ahorro total</span><b>− $22.426</b></p><p><span>Envío</span><b>Gratis</b></p><p><strong>Total</strong><strong>$89.784</strong></p></div></section><aside className="next-steps"><h2>Próximos pasos</h2>{[["✓","Pedido confirmado","Listo. Te enviamos el comprobante."],["2","Preparación","Armamos y controlamos tu pedido."],["3","En camino","Vas a recibir el código de seguimiento."],["4","Entrega","La persona que recibe debe ser mayor de edad."]].map(([number,title,copy]) => <div key={title}><span>{number}</span><p><strong>{title}</strong><small>{copy}</small></p></div>)}<p className="help-order">◯ ¿Necesitás ayuda? Escribinos con tu orden <b>QG-2026-18472</b>.</p></aside></div></div></main></>;
}
