import type { Metadata } from "next";
import { notFound } from "next/navigation";
import productReference from "@/design-reference/05-producto.png";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { ProductCard } from "@/components/product-card";
import { ReferenceCrop } from "@/components/reference-crop";
import { TrustStrip } from "@/components/trust-strip";
import { BagIcon, CheckIcon, HeartIcon } from "@/components/icons";
import { getProduct, storeProducts } from "@/lib/store-data";

type ProductPageProps = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return storeProducts.map((product) => ({ slug: product.slug }));
}

export async function generateMetadata({ params }: ProductPageProps): Promise<Metadata> {
  const product = getProduct((await params).slug);
  return product ? { title: `${product.name} | QuilGym`, description: product.detail } : { title: "Producto no encontrado | QuilGym" };
}

export default async function ProductPage({ params }: ProductPageProps) {
  const product = getProduct((await params).slug);
  if (!product) notFound();
  const related = storeProducts.filter((item) => item.slug !== product.slug).slice(0, 4);

  return <><Header/><main className="product-page"><div className="container"><p className="breadcrumb">Inicio / {product.category} / {product.brand} / {product.name}</p><section className="product-hero"><div className="product-gallery"><div className="gallery-thumbs">{[1,2,3,4].map((item) => <button type="button" key={item}><ReferenceCrop source={productReference} crop={{ x: 175, y: 92, width: 545, height: 520 }} alt=""/></button>)}<button type="button" className="video-thumb">▶<span>VIDEO</span></button></div><ReferenceCrop source={productReference} crop={{ x: 175, y: 92, width: 545, height: 520 }} alt={product.name} className="product-main-image" priority/></div><div className="product-buybox"><div className="buybox-brand">{product.brand}<button type="button" aria-label="Guardar en favoritos"><HeartIcon/></button></div><h1>{product.name}</h1><p className="rating">★★★★★ <strong>{product.rating}</strong> <span>({product.reviews} reseñas verificadas)</span></p><p className="buybox-price">{product.price} {product.oldPrice ? <del>{product.oldPrice}</del> : null} <span>10% OFF</span></p><strong className="payment-copy">3 cuotas sin interés de ${(product.priceValue / 3).toLocaleString("es-AR", { maximumFractionDigits: 0 })}</strong><p className="transfer-price">${Math.round(product.priceValue * .9).toLocaleString("es-AR")} con transferencia bancaria</p><div className="option-group"><span>Sabor: Neutro</span><div><button type="button" className="is-active">Neutro</button><button type="button">Limón</button><button type="button">Frutos rojos</button></div></div><p className="variant-warning">⚠ La variante Frutos rojos no está disponible en 300 g.</p><div className="option-group"><span>Presentación</span><div><button type="button">150 g · $21.900</button><button type="button" className="is-active">300 g · {product.price}</button><button type="button">600 g · Sin stock</button></div></div><div className="buy-actions"><div className="quantity"><button type="button">−</button><span>1</span><button type="button">+</button></div><div><button type="button" className="button button--outline"><BagIcon/> Agregar al carrito</button><a className="button button--dark" href="/carrito">Comprar ahora</a></div></div><div className="shipping-calculator"><strong>Calculá tu envío</strong><label htmlFor="postal-code">Código postal</label><div><input id="postal-code" defaultValue="1878"/><button type="button">Calcular</button></div><p><CheckIcon/> Llega entre el martes 6 y miércoles 7. Envío gratis.</p></div></div></section><TrustStrip/>
      <section className="product-info-section"><div className="section-heading"><div><h2>Todo sobre esta creatina</h2><p>Información clara para entender el producto y decidir según tu rutina.</p></div></div><div className="feature-cards">{[["▣","Para qué sirve","Aporta creatina monohidrato para complementar rutinas de fuerza, potencia o ejercicios repetidos."],["✣","Beneficios prácticos","Presentación sin azúcar agregada, sabor neutro y fácil de integrar en agua o bebida habitual."],["♙","Para quién es","Personas adultas que entrenan y buscan una opción simple, con porción medida y rotulado claro."],["◌","Preferencias","Sin TACC según rótulo vigente. Revisá siempre la información del envase."]].map(([icon,title,text]) => <article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="product-facts-grid"><div className="accordions">{[["Ingredientes","Creatina monohidrato micronizada. No contiene saborizantes en la variante Neutro."],["Porciones","Contenido neto 300 g. Rinde 60 porciones de 5 g cada una."],["Modo de uso","Disolver una medida en 200–250 ml de agua o bebida."],["Advertencias","Producto para personas adultas. No superar la porción indicada."],["Conservación","Mantener en lugar fresco y seco."]].map(([title,text], index) => <details open={index === 0} key={title}><summary>{title}</summary><p>{text}</p></details>)}</div><aside className="nutrition-panel"><h3>Información nutricional</h3><p>Porción 5 g (1 medida) · 60 porciones</p>{[["Valor energético","0 kcal"],["Carbohidratos","0 g"],["Proteínas","0 g"],["Grasas totales","0 g"],["Sodio","12 mg"],["Creatina monohidrato","5 g"]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</aside></div></section>
      <section className="product-faq"><h2>Preguntas frecuentes</h2>{["¿Tiene sabor?","¿Cuánto rinde?","¿Se puede combinar con proteína?","¿Cómo conservo el producto?"].map((item,index) => <details open={index === 0} key={item}><summary>{item}</summary><p>{index === 0 ? "La variante Neutro no incorpora saborizantes y puede mezclarse con agua u otra bebida." : "La información declarada puede variar según la presentación elegida."}</p></details>)}</section>
      <section className="verified-reviews"><div className="section-heading"><div><h2>Reseñas verificadas</h2><p>Opiniones de compradores para ofrecer una lectura completa.</p></div></div><div className="review-summary"><div className="rating-card"><strong>{product.rating}</strong><span>★★★★★</span><p>{product.reviews} reseñas verificadas</p></div>{["Muy práctica para mi rutina", "Buen tamaño y rotulado claro", "Volvería a comprar"].map((title,index) => <article className="review-card" key={title}><span>COMPRA VERIFICADA</span><strong>{["Lucía M.","Matías R.","Carla G."][index]}</strong><h3>{title}</h3><p>La entrega fue rápida y el producto vino sellado. Me gustó poder retirar en Quilmes.</p></article>)}</div></section>
      <section className="similar-products"><div className="section-heading"><div><h2>Productos similares</h2><p>Otras opciones con presentaciones y precios para comparar.</p></div></div><div className="product-grid">{related.map((item) => <ProductCard product={item} key={item.slug}/>)}</div></section>
    </div></main><Footer/></>;
}
